import java.util.ArrayList;
/*
The sequence of triangle numbers is generated by adding the natural numbers. So
the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten
terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:
 */
public class HighlyDivisibleTriangle {
    public static void main(String[] args) {
       divisibleTriangleNumbers(4);
       divisibleTriangleNumbers(10);
       divisibleTriangleNumbers(500);
    }

    public static void divisibleTriangleNumbers(int num) {
        ArrayList<Integer> divisors = new ArrayList<>();
        int sum = 0;
        for (int i = 0; i <= num; i++) {
            sum += i;
        }

        for (int i = 1; i <= sum; i++) {
            if (sum % i == 0) {
                divisors.add(i);
            }
        }
        System.out.println(num + " ==> " + sum + ": " + divisors);


    }
}
