public class EvenFibonacciNumbers {
    public static void main(String[] args) {
        System.out.println(fibonacciSequence(10));
    }
    
    /*
    Each new term in the Fibonacci sequence is generated by adding the previous
    two terms. By starting with 1 and 2, the first 10 terms will be:
    
    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
    
    By considering the terms in the Fibonacci sequence that do not exceed the 
    nth term, find the sum of the even-valued terms.
     */
    
    public static int fibonacciSequence(int index) {
        int sum = 0;
        int f0 = 0;
        int f1 = 1;
        int f2 = 1;
        
        for (int i = 3; i <= index; i++) {
            f0 = f1;
            f1 = f2;
            f2 = f0 + f1;

            if (f2 % 2 == 0) {
                sum += f2;
            }
        }
        return sum;

    }
}
